### ISSUE TITLE
Apache won't start due to missing folders

### ISSUE THREAD

**Issue by Bogardo** [mennoboer/menpro#2]
After installing MenPro, Apache is not able to start.
When running the `debug.bat` file in the `bin` directory I get the following error:

```
AH00112: Warning: DocumentRoot [C:/Server/www/_default_] does not exist
(OS 2) The system cannot find the file specified. : AH02297: Cannot access directory 'C:/Server/bin/Apache/2.4.17/logs/' for log file 'logs/access.log' defined at 'C:/Server/bin/Apache/2.4.17/conf/httpd.conf:287'
AH00014: Configuration check failed
```

**Comment by john-webverzorgers** [comment]
Same goes for the "logs" folder in the apache/<version>/ folder.
Create "<path\to\menpro\bin\Apache\<version>\logs"

**Comment by mennoboer** [comment]
In the next version, MenPro 1.2.1, this issue is solved.
