### ISSUE TITLE
Menpro stops working adding the first vhost

### ISSUE THREAD

**Issue by john-webverzorgers** [mennoboer/menpro#4]
It is not clear that a directory should be set first. Adding a vhost and saving it without adding a directory first crashes menpro.

**Comment by john-webverzorgers** [comment]
A vhost should be added by right clicking on the directory name

**Comment by john-webverzorgers** [comment]
If you change the WWW location you have to create the _default_ folder again on this location.

**Comment by mennoboer** [comment]
This is solved in MenPro 1.2.1, soon to be released.
